### ISSUE TITLE
duyurular kısmında url (link) parse error

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#100]
Raporlayan: 30 mg paroksetin

duyurular kısmına atılan link itü sözlük'te düzgün çalışırken instela'da bir kısmı aktif olmuyor. 

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/215f71f7241f0a6de5b152c080a88ebd12461.png)

**Comment by cagataygurturk** [comment]
Regex olarak wordpress'in kodunu kullanıyorum.

Markdown ilginç olabilir belki bold ve italiğe de mi izin versek?

**Comment by cagataygurturk** [comment]
Regex olarak wordpress'in kodunu kullanıyorum.

Markdown ilginç olabilir belki bold ve italiğe de mi izin versek  @thehivecluster/issue-trackers ?
