### ISSUE TITLE
Olaylar kısmından ...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#121]
Raporlayan: roketadam

Olaylar kısmından takip ettiğim yazarla ilgili bilirim geldiğinde o yazarın nickname'ne tıkladığımda 404 hatası almaktayım.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/d2340244cafadd90b9df9faf3a26920330385.png)

**Comment by cagataygurturk** [comment]
Fixed by https://github.com/thehivecluster/itusozluk-v5/commit/a502bd5c1667d6c44b718f79b5748e2102271d75
