### ISSUE TITLE
#135'e ek olarak int...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#136]
Raporlayan: 30 mg paroksetin

#135'e ek olarak internet explorer tarayıcısında sayfa aşağı doğru çekilemiyor ve dolayısıyla "yeni giri" butonu çıkmıyor. yani şu an için internet explorer kullanan bir yazar giri yazamıyor sanıyorum.  

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/ffa315e871462f65095af69e6cfb7aed1496.png)

**Comment by leopoldleopoldovic** [comment]
Bende böyle bir sıkıntı yok. Bendeki sıkıntı da, kategoriler kısmına ilişkin. "diğer" seçeneği görüntülenmiyor, orada çıkan üç-beş kategori seçilebiliyor sadece.

**Comment by cagataygurturk** [comment]
galiba bu sorun düzeldi sonradan
