### ISSUE TITLE
instela'yı google'de aratmak

### ISSUE THREAD

**Issue by 30mgparoksetin** [thehivecluster/instela-issues#146]
instela.com'un google arama sonuçlarındaki durumunu merak ettim. 

sonuç şöyle: http://i.hizliresim.com/rm9oR7.png

acaba tam anlamıyla hazır olduğunda mı ilk sıralarda çıkması için çalışma yapılacak?

**Comment by cagataygurturk** [comment]
Henuz google'da engelli evet
