### ISSUE TITLE
kullanıcı kendi girisini favori ekleyebiliyor

### ISSUE THREAD

**Issue by 30mgparoksetin** [thehivecluster/instela-issues#151]
kullanıcının istatistiklerine yansıyor mu bilemiyorum ama kendi girimizi favori ekleyebiliyoruz. belki sayfayı yenileyince kaybolur diye baktım ama favori sayısı aynı kalıyor. tıpkı "kendi girinize oy veremezsiniz" uyarısı gibi "kendi girinizi favori ekleyemezsiniz" uyarısı verilebilir.

**Comment by cagataygurturk** [comment]
eklemeye izin veriyoruz
