### ISSUE TITLE
panel/settings beyaz ekran hatası 

### ISSUE THREAD

**Issue by 30mgparoksetin** [thehivecluster/instela-issues#153]
hatanın meydana gelişi şu şekilde: panel/settings adresindeki "profilimde takip ettiğim kişiler başkalarınca görülebilsin" seçeneğindeki tik işaretini tıklayıp kaldırdıktan sonra "kaydet" butonuna bastıktan sonra instela'da bir kasılma oluyor ve biraz bekledikten sonra beyaz bir ekran geliyor ve de işemimiz yapılamıyor yani "profilimde takip ettiğim kişiler başkalarınca görülebilsin" seçeneği şu an için devre dışı bırakılamıyor. diğer seçeneklerde denemedim. 

birinci adım: http://i.hizliresim.com/XD4a7o.png

ardından gelişen hata: http://i.hizliresim.com/MPJOYa.png

**Comment by cagataygurturk** [comment]
genel sorun, ayarlarda çözemediğim bir takılma var.
