### ISSUE TITLE
Nesillere Göre Yazar Dağılımı 0'dan başlıyor.

### ISSUE THREAD

**Issue by az3** [thehivecluster/instela-issues#159]
itusozluk.com üzerinde, "nesillere göre yazar dağılımı" istatistik sayfasında sorun var.
https://www.itusozluk.com/stats.php?op=18
Muhtemelen db'de bir şeyi elle değiştirdik, not alalım.

![screenshot](http://i.hizliresim.com/BRvB1V.png)

**Comment by cagataygurturk** [comment]
gece düzelmiş olur
