### ISSUE TITLE
itü sözlük'te davet edilecek kişi e-posta textbox'una boş giriş yapılabiliyor

### ISSUE THREAD

**Issue by 30mgparoksetin** [thehivecluster/instela-issues#160]
https://www.itusozluk.com/panel/invites adresindeki yazar davet etme ekranındaki e-posta kısmına boş giriş yapıldığında davet gönderiyor ve davet hakkımızdan 1 adet düşüyor. "geçerli bir e-posta girmeniz gerekiyor!" uyarısı vermiyor. 

ekim ayından beri olan bir problem bu: http://i.hizliresim.com/bgkWEV.png

**Comment by cagataygurturk** [comment]
instela'ya geçeceğimiz için yakında düzeltilmesine çok da gerek yok ama teşekkürler.
