### ISSUE TITLE
visplash görsel ekleme

### ISSUE THREAD

**Issue by collonsdedeu** [thehivecluster/instela-issues#161]
url üzerinden görsel yüklemek istediğimde uzun linki olan görselleri sistem bazen kabul etmiyor. 

![z1](https://cloud.githubusercontent.com/assets/10278459/5607410/c2f0f55a-9463-11e4-8f8d-b3e26d0d572c.jpg)
![z2](https://cloud.githubusercontent.com/assets/10278459/5607411/c2f8a5d4-9463-11e4-8be6-64af7ee778ec.jpg)

resimlerde görüldüğü üzere (kaydet'e tıklamadan önce/sonra) kaydet'e tıkladıktan sonra "başlık" içindeki yazı siliniyor ve görsel yüklenmiyor. bazen dedim zira her zaman olan bir şey değil bu. url uzayınca daha sık oluyor gibi, kısa url'lerde (mesela doğrudan imgur url'lerinde) pek bir soruna rastlamadım. bilgisayardan eklerken de ilerleme %0'da takılıyor, işlemi iptal edip tekrar denemek de çoğunlukla işe yaramıyor. 

![z3](https://cloud.githubusercontent.com/assets/10278459/5607426/bb90bdc6-9464-11e4-820a-af5ef8c69e07.jpg)

gerçi visplash'in instela'ya entegre edileceği, ayrı bir site olmayacağı söylenmişti ama bir sıkıntı varsa çözülse ve instela'ya sorunsuz entegrasyon sağlansa iyi olur gibi.

**Comment by cagataygurturk** [comment]
doğru, visplash'i de instela'nın içine gömüyoruz bu sorun da otomatik çözülmüş olur. o sebepten kapatıyorum bug'ı.
