### ISSUE TITLE
itü sözlük v5'te tasarımda oluşan bir bozukluk

### ISSUE THREAD

**Issue by 30mgparoksetin** [thehivecluster/instela-issues#165]
daha önce sözlüğe yazmıştım fakat buraya da yazmak istedim. belki instela için bir yararı olur.

öncelikle bozukluk şu: http://i.hizliresim.com/bgkNjb.png

meydana gelişi ise aşağıdaki şekilde:

- profil sayfamızdan bir giri editliyoruz.
- giri editleme ekranı açıkken sol frame'den bir başlığa tıklayarak açıyoruz.
- tarayıcımızın geri tuşuna basıyoruz. 

tüm bu adımlardan sonra yukarıda görseli verilen bozukluk ortaya çıkıyor.

**Comment by cagataygurturk** [comment]
itü sözlük hatalarını burada bildirme lütfen.
