### ISSUE TITLE
akıllı bakınız balonu

### ISSUE THREAD

**Issue by collonsdedeu** [thehivecluster/instela-issues#167]
imleci bir akıllı bakınızın üzerine getirdiğimizde itü'deki gibi içinde ne yazdığını gösteren bir baloncuk çıkmıyor. yıldızın içindekini sadece tarayıcının sol altındaki bağlantı açıklamasıyla görebiliyoruz.

**Comment by collonsdedeu** [comment]
temcit pilavı gibi ısıtıp sunmak istemiyorum ancak son halinde de yıldızın kendisi çıkıyor balonun içinde, yıldızın içindeki metin değil.

**Comment by cagataygurturk** [comment]
estağfurullah niye temcit pilavı olsun buranın amacı hataları düzeltmek.
