### ISSUE TITLE
sanırım ekran gör...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#168]
Raporlayan: bukkakelemun

sanırım ekran görüntüsünde gözükmüyor ama twitter ikonu girilerin çerçeveleriyle tam hizalı değil veya öyleyse bile görsel olarak değil. tam hizalı yapılabilir. yeni giri butonu tam hizalıyken twitter ikonu birazcık taşmış gibi.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/3a59e21593feb04cc172af263bf6db3e4914.png)

**Comment by cagataygurturk** [comment]
matematiksel olarak tam ortalanmış durumda ikonun kendisi asimetrik diye öyle gözüküyor algılanmış olabilir belki.
