### ISSUE TITLE
birisi girinizi sosyal medyada paylaştı bildirimi

### ISSUE THREAD

**Issue by sageeth** [thehivecluster/instela-issues#171]
birisi girimizi sosyal medyada paylaştığında emailimize bildirim geliyor. bildirimde giriye bağlantı verilmiş. eğer maildeki o bağlantıya tıklarsanız instela üzerinden giriye gidiyor ve emaile bir bildirim daha gidiyor "giriniz sosyal medyada paylaşıldı" diye. üç dört kere tıkladım maildeki bağlantıya, her seferinde yeni bildirim geldi maile.

**Comment by sageeth** [comment]
Buna ek olarak ben maillerde o giriye tekrar gitmesem de birkaç kere daha bildirim geldi maile ancak sözlükte herhangi bir bildirim yok paylaşım olduğuna dair. Sanırım farklı bir durum sözkonusu.

**Comment by cagataygurturk** [comment]
Hangi mail servisini kullaniyorsun? Maili okudugun url yi paylasabilir
misin? Ve de giri nosunu.

Sen tiklamiyorsan hakikaten birileri paylasiyor olabilir

**Comment by sageeth** [comment]
Gmail. 

https://mail.google.com/mail/u/0/?tab=wm#inbox/14ac197e90627152

giri nosu: @13651829 

mail'deki link direkt şuraya yönlendiriyor: https://tr.instela.com/schindler-s-list--@13651829

Ben tıkladıkça mail geliyor orası kesin. Ama tıklamadığıma emin olduğum saatlerde de bildirim geldi maile, biri paylaşsaydı v5'te de bildirim gelmez miydi?

**Comment by sageeth** [comment]
Firefox v34. Şu an bahsettiğim adımları gerçekleştirdikten sonra artık gelmiyor maile bildirim. en son 3 saat önce geldi.

**Comment by sageeth** [comment]
TSİ 17:44'te tekrardan kendi kendine bir bildirim daha geldi maile. Acaba ilk paylaşan kişinin paylaşımına o sitede tıklandıkça mı uyarı geliyor diye saçma bir düşünceye kapıldım.

**Comment by cagataygurturk** [comment]
gerçekten paylaşılmış girin sa9dad9 hayrını gör hoşuna gitti mi mail gelmesi?
