### ISSUE TITLE
instela.fm yayın bi...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#173]
Raporlayan: sageeth

instela.fm yayın bilgisini gösteren kısımda dinleyen yazarlara ait thumbnailler çoklu gösteriliyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/6a21a352ca57507ef2e42c7d32e8d25610917.png)

**Comment by sageeth** [comment]
gözükmemiş:

http://i62.tinypic.com/2141mwk.png
