### ISSUE TITLE
itü'ye yönlendirme

### ISSUE THREAD

**Issue by collonsdedeu** [thehivecluster/instela-issues#182]
adres satırına es.instela.com yazdığımızda otomatik tr.instela.com'a yönlenirken p.instela.com yazdığımızda itusozluk.com'a yönleniyor. bilinçli yapılmış bir şey midir acaba, hani "eski dandik site" gibi?

**Comment by cagataygurturk** [comment]
p.instela.com dillerle ilgili bir subdomain değil, push notifikasyonların gönderildiği bir sunucuya ait dolayısıyla son kullanıcıyı ilgilendirmiyor. ama keşfetmişsin :)
