### ISSUE TITLE
şu kısıma bir de ...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#184]
Raporlayan: içinden kan sızan tatlı

şu kısıma bir de takip ettiğimiz yazarlar, (kanka, badi) sekmesi eklense çok iyi olacak.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/38fd7395826b4eadb950c1f3f2d5677b19692.png)

**Comment by icindenkansizantatli** [comment]
ayrıca yan tarafta parantez içerisinde takip ettiğimiz yazar veya yazarlardan kaç giri var ise belirtilirse, ayriyetten tıklayıp kontrol etme zahmetine girilmez. bunun örneği ekşi'de var, son derece de kullanışlı.
