### ISSUE TITLE
sohbet kutusu açıl...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#191]
Raporlayan: içinden kan sızan tatlı

sohbet kutusu açıldıktan sonra kapanmıyor. yani kapatmak için bir buton yok, tekrar sohbet butonun üzerine tıkladığımızda da kapanmıyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/6f2188ccd125498c73ee62ff5b1ad37013535.png)

**Comment by cagataygurturk** [comment]
Kapanacak şekilde ayarlanmadı sadece tek girinin olduğu yerde çıkıyor zaten
