### ISSUE TITLE
isminde türkçe kar...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#194]
Raporlayan: arcticfur ve elem

isminde türkçe karakter bulunan yazarların açtığı duyurular ve duyurulara verdiği cevaplar görünmemekte.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/48a5b78f82956c3398d220f62a5c195415511.png)

**Comment by cagataygurturk** [comment]
bu itü sözlük'le ilgili bir sorun geçiş tamamen tamamlanınca yok olacak.

**Comment by cagataygurturk** [comment]
hepsinde olmuyor bu arada
