### ISSUE TITLE
Stored Xss

### ISSUE THREAD

**Issue by ynsy** [thehivecluster/instela-issues#197]
Input kontrolu yapılmadığı için heryerde stored xss mevcuttur bu sayede remote olarak javascript kodları çalıştırılabiliyor. 

örneğin; 

https://tr.instela.com/user/testkullanici--180079

**Comment by cagataygurturk** [comment]
Aslında input control var, yazılan html kodları html kodlarına çevrilip saklanıyor ama sonra string parser'da ne hikmetse htmlspecialchars_decode yazmışım. Şu an benzer tüm hataların topluca çözülmüş olması lazım kontrol edebilir miyiz? 

@az3

**Comment by az3** [comment]
Önce her şeyi escape et, sağlama al, sonra gereklileri açarsın. Güvenlik, şekil bozukluğundan önce gelir.
#203 mesela bununla ilgili. Bazı exceptionlar eklemen lazım, String parser fonksiyonunu regexp ile temize çeksen daha iyi.

**Comment by ynsy** [comment]
entirilerde şuan için sıkıntı yok fakat mesaj bolumunde aynı sıkıntı haala var. 
![xss](https://cloud.githubusercontent.com/assets/2750432/5776499/0759a3be-9d91-11e4-98da-52a0761ec3d8.PNG)

**Comment by cagataygurturk** [comment]
bu sorunlar çözüldü başka yerlerde var mı ikinci bir gözün test etmesine ihtiyaç duyuyorum.
