### ISSUE TITLE
engellen(mey)en kişiler

### ISSUE THREAD

**Issue by collonsdedeu** [thehivecluster/instela-issues#202]
teknik bir sorun mu bilmiyorum fakat hem itü'de, hem instela'da karşıma çıkan bir şey bu.

https://tr.instela.com/kaynak-belirtilmeden-alinti-yapilmis--1406946
https://www.itusozluk.com/goster.php/kaynak+belirtilmeden+al%FDnt%FD+yap%FDlm%FD%FE

başlığın ilk girisi gxix tarafından yazılmış. kendisi benim engelli listemde olmamasına rağmen, başlığı itü'de getirdiğimde ilk giri olarak azureel'in 2. sıradaki girisi geliyor (yukarıda da gizli (1) yazıyor). sadece gizli'nin üzerine tıklayarak gxix'in girisini görebiliyorum. başlığı instela'da getirdiğimde ise doğrudan azureel'in girisiyle başlıyor ve gxix'in girisini hiçbir şekilde göremiyorum.

http://i.imgur.com/YB4b6pO.jpg
http://i.imgur.com/naUaeFP.jpg

bu engellenenler hususunda şu an örneklendiremeyeceğim hatalarla daha önce de karşılaşmıştım. yanlış bir şeyler var sanki orada.

**Comment by cagataygurturk** [comment]
malum giriyi gizlemişsin zamanında :) açtım şimdi tekrar görebilirsin.

itü sözlük'te son zamanlarda bazı hatalar düzelttim konuyla ilgili. instela'da baştan dikkatlice yazıldı.
