### ISSUE TITLE
tırnak işaretleri ...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#203]
Raporlayan: sageeth

tırnak işaretleri ekran görüntüsündeki gibi bozuk çıkıyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/4a11552e0a4249082eb294cff603a1d616007.png)

**Comment by az3** [comment]
#197 ile ilgili yapılan düzeltmeden etkilenmiş olabilir.
Yakında düzeltilir, acelesi yok.

**Comment by cagataygurturk** [comment]
Biliyorum gece farkettim ben de
