### ISSUE TITLE
instela kayıt olma ekranında olmayan bir mail servisi yazmak

### ISSUE THREAD

**Issue by mehmetkucuk** [thehivecluster/instela-issues#209]
kayıt olurken rastgele mail yazmak: http://i.hizliresim.com/z2j5o9.png

kayıt gerçekleşiyor: http://i.hizliresim.com/Q4LBoG.png

sanıyorum geçerli bir mail servisi girmesi konusunda kullanıcıyı uyarmak gerekiyor.

**Comment by az3** [comment]
Yapısı gereği, mail validation çok yavaş ve asenkron bir işlem, bence ön tarafta böyle bir cevap vermesi gayet sağlıklı.

**Comment by cagataygurturk** [comment]
Maili onaylammamis insanlarin yetkileri kisitli
