### ISSUE TITLE
instela kayıt olma ekranındaki seçeneklere "kullanıcı adı" kısmı eklenmeli

### ISSUE THREAD

**Issue by mehmetkucuk** [thehivecluster/instela-issues#210]
http://i.hizliresim.com/Ezm8vn.png adresinde görülen ekranda yalnızca ad-soyad, e-mail ve şifre seçenekleri var. böyle olunca sanki instela'ya gerçek ad ile üye olunup yalnızca gerçek ad ile yazılabilecekmiş gibi bir hava veriyor.

**Comment by az3** [comment]
Orası hakikaten öyle, gerçek isim istiyoruz.
username isteme (yani rumuz belirleme sahfası), sonraki sayfada gelecek sanırım?

**Comment by cagataygurturk** [comment]
Sonraki ekranda geliyor ozellikle oyle ayarlandi

**Comment by mehmetkucuk** [comment]
ben de öyle düşünmüştüm ama yine de danışmak istedim. twitter da bu yöntemi kullanıyor. 

önce isim soyisim mail şifre: http://i.hizliresim.com/jvgnLL.png
sonra kullanıcı adı: http://i.hizliresim.com/2Y6Zy2.png
