### ISSUE TITLE
Sürekli siteye girm...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#215]
Raporlayan: tekkalan

Sürekli siteye girmeme rağmen girmedi görünüyor.

tarayıcı: chrome.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/ed0431da35f087c786d89f0294ccf5496695.png)

**Comment by cagataygurturk** [comment]
sözlük penceresini kapayıp dener misin?
