### ISSUE TITLE
duyulara yapılan yo...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#219]
Raporlayan: leopold leopoldoviç

duyulara yapılan yorumlarda yazar isimleriyle ne olduğunu çözemediğim bir link birbirine giriyor. 

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/072303ede0f8e8695e5a141ce987e7dd15496.png)

**Comment by cagataygurturk** [comment]
refresh lütfen
