### ISSUE TITLE
şifre doğru giriş...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#221]
şifre doğru giriş yapamıyorum...

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/435f962c3ef2ce7d02445cba5adfd93c19969.png)

**Comment by cagataygurturk** [comment]
itü sözlük'ten giriş yapılabiliyor mu?

**Comment by sageeth** [comment]
özel karakterlerin kullanılması sorunu çözüldü mü acaba?
