### ISSUE TITLE
nick ve zaman yazıl...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#227]
Raporlayan: sokaktan gelen adam

nick ve zaman yazıları üst üste binmiş

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/0afb76098a4af7773f9b0fd26666090919969.png)

**Comment by mehmetkucuk** [comment]
sayfayı yenilediğinde geçmesi gerekiyor. (bkz: #217)
