### ISSUE TITLE
statülere ne oldu?

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#240]
Raporlayan: gölgeningücü

statülere ne oldu?

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/5486e3db79aa1e698e81f8bfb4f2c0ab10205.png)

**Comment by mehmetkucuk** [comment]
artık kullanılmayacak yerine "puan ve nişan sistemi" yazılıyor azureel tarafından.  
(bkz: instela puan ve nişan sistemi)
(bkz: https://www.itusozluk.com/goster.php/instela+puan+ve+ni%FEan+sistemi/@13625831)
