### ISSUE TITLE
instela okurları için "şikayet et" butonu

### ISSUE THREAD

**Issue by mehmetkucuk** [thehivecluster/instela-issues#269]
son can sıkıcı hukuki olaylardan sonra aklıma gelen buton. 

okurlar hukuken sakınca yaratabilecek olan girileri bu butonla şikayet edebilir ve gönüllü birkaç avukat instela yazarı da bu şikayeti değerlendirip silebilir diye düşündüm. tabii okurlar hemen mahkemeye koşmazlarsa.

**Comment by cagataygurturk** [comment]
http:/tr.instela.com/support
