### ISSUE TITLE
üye girişi yapamı...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#270]
üye girişi yapamıyorum... hem itüsözlük sayfasından hem de instela sayfasından giriş yapılamıyor...

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/d7a0eb15484eeea973dc0c69f0fb402a7748.png)

**Comment by cagataygurturk** [comment]
instela'yla ilgili bir sorun gibi gözükmüyor
