### ISSUE TITLE
Mobilde kendi kendine çıkış yapıyor. 

### ISSUE THREAD

**Issue by sayz** [thehivecluster/instela-issues#273]
http://imgur.com/4PdOzvy önceden en azından belli bir süre girmezsek çıkış yapıyordu,  tekrar giriş yapınca tekrar girmeye gerek olmuyordu sitede gezerken. Ama şimdi normal giriş yapınca sitede dururken atıyor seni  ve tekrar giriş yapınca da bazen kabul ediyor bazen etmiyor keyfine göre. İyice bozuldu bugün.

**Comment by cagataygurturk** [comment]
tekrar olursa haber ver lütfen.

**Comment by sayz** [comment]
Az önce tekrar tekrar başıma geldi. Normal gezinirken atıyor mobilde.

**Comment by sayz** [comment]
sadece mobilde değil şu anda normal sitede de aynı problem var. #327 burda da bi arkadaş yazmış hatta

**Comment by cagataygurturk** [comment]
Sorunu biliyor ve cozmeye calisiyoruz. Gieis yaparken sifremi hatirlayi
secmek gecici cozum olabilir

**Comment by cagataygurturk** [comment]
tekrar gerçekleşirse haber ver lütfen çözüldü gibi.

**Comment by sayz** [comment]
şu anda hala devam ediyor. problem. hatta giriş dahi yapamıyorum. şansa bazen giriş yapıyor o da ancak birkaç saniyeliğine. **beni hatırla** devamlı seçili zaten pek bir etkisi yok kanımca.
