### ISSUE TITLE
Facebook'ta paylaş ...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#30]
Raporlayan: hansvoralberg

Facebook'ta paylaş butonuna tıkladıktan sonra paylaşılacak kişiler listesini seçmek istediğimde drop down menü açık pencerenin altında kalıyor ve görünmüyor. Pencereyi büyütmeme rağmen tıklanamayacak bir bölgede açılıyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/970c02d65d40cb448010e35425df197a6312.png)

**Comment by cagataygurturk** [comment]
Facebook penceresini facebook yönetiyor zaten birşey yapamayız ki
