### ISSUE TITLE
Daha önce sildiğim...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#310]
Raporlayan: ozanudazai

Daha önce sildiğim giriler geri gelmiş. Ayrıca en sevilmeyenlerim girim bu kadar çok değildi. hemen hemn eksi oy almış bütün girilerim en sevilmeyen olarak gözüküyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/49a23ce2bceaa05c67589d70142b060328587.png)

**Comment by sageeth** [comment]
Şu an veritabanı ile ilgili işlemler yapılıyor sanırım. Eski silinmiş girilerin geri gelmesi bundandır sanırım. En sevilmeyenler kısmına gelince zannedersem belirli bir algoritmaya göre yazarların tüm girileri en kötüden iyiye doğru listeleniyor "en sevilmeyenler" sekmesinde. Bunun 10-15 giri ile sınırlandırılması makuldür diye düşünüyorum şahsen. Ayrıca en sevilmeyenler sekmesi yeni bir feature olarak sadece yazarın kendisine gözüküyor. Diğer yazarların en sevilmeyen eserlerini göremiyoruz.
