### ISSUE TITLE
gece görüş modu y...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#323]
Raporlayan: chnhf

gece görüş modu yok, ekşide kullanıyorum gece görüş modunu ve fevkalade. Arka planın siyah olması, okunan yazıya olan odağı bile arttıyor kanımca. böyle bir durumunuz var mı? gece modu gibi bir mod ekleme durumu?

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/isconzf5y8i5d3cmiv7j2zwlo2blf0gytsnhs3mrb5wo88bq4j.png)

**Comment by cagataygurturk** [comment]
ayarlar->görünüm
