### ISSUE TITLE
Fotoğrafımın kald...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#333]
Fotoğrafımın kaldırılmasını istiyorum. Benimle ilgili yazılan bilgilerin tamamı yalan ve yanlış. Hepsi kaldırılsın.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/bedm20ryjrxs16d29bcuij5nrfixogv0u9nx9ews6tl80zaaan.png)

**Comment by az3** [comment]
sigh...

**Comment by mueddib** [comment]
sağ tarafa bakınca görüyoruz ki bir burak aksak ismi geçiyor.
