### ISSUE TITLE
kendi girime yorum y...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#348]
Raporlayan: pedagojik formasyon

kendi girime yorum yapılınca notifikasyon gelmeli.

yorum yaptığım bi giriye başka yorum yapılınca da notifikasyon gelmeli.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/b4ozy44n9nekimbn2pg6of0wiwcupl00pozot4b2rqn9czxfpd.png)

**Comment by cagataygurturk** [comment]
denedim notifikasyon gidiyor @burakt82
