### ISSUE TITLE
selamlar, öncelikle...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#354]
Raporlayan: insan demosu

selamlar, öncelikle instela süper fikir. tebrik ederim. ancak şöyle bir bildirim yapmak istiyorum.

duyurular bölümünde bir yorum yazdığımda bunu silemiyor muyum? ya da bildirimlerini sessize almam gibi bir seçenek yok mu? söyleyecek başka bir şeyim olmamasına rağmen sürekli bu duyuru konusu ile ilgili bildirim almak biraz can sıkıcı.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/3ycuvv85jmsf26fpjbvi1ji4q1dcdg9gema9ije167h8exyx8t.png)

**Comment by cagataygurturk** [comment]
her duyurunun üzerinde bir göz ikonu var oraya tıklarsan bildirimler durur.
