### ISSUE TITLE
Mesaja tıkladığı...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#387]
Raporlayan: sonra düşünürüz

Mesaja tıkladığımda aşağıdaki şekilde hata vermektedir.
Unauthorized
Tarayıcı : Chrome

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/09a0yckqat2qk0ixhcmdxuxev8t1d3tec3eafz1qs4gd4yambw.png)

**Comment by cagataygurturk** [comment]
çekirge olduğundan
