### ISSUE TITLE
İtüsözlük'teki h...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#406]
Raporlayan: Serhan Turan

İtüsözlük'teki hesabım instela'ya geçmemiş gözüküyor. Yani instela'ya giriş yapmadan kendimi aratınca buluyorum. Ama kullanıcı adım ve şifremi yazınca girilmiyor. E-posta adresim ve şifremi yazınca ise yeni hesap gibi açılıyor. Bu çekirge olduğum için mi acaba ?

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/60mdpnql0bygip8q3ufwvy0xwx56oomvo98ewz0wbyctolkrgz.png)

**Comment by cagataygurturk** [comment]
destek e yazın
