### ISSUE TITLE
ah be bir de gece mo...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#416]
Raporlayan: chnhf

ah be bir de gece modu veya tema seçme gibim bişiler olsa tadından yenmez efendi hazretlerim.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/ert3hetlc67mimcy4301n6wvlkjv93pnvirdwly8r5v9s88xc8.png)

**Comment by cagataygurturk** [comment]
ayarlar -> görünüm -> v4
