### ISSUE TITLE
Text box'ı kapatmak

### ISSUE THREAD

**Issue by collonsdedeu** [thehivecluster/instela-issues#418]
"bu konuda benim de söyleyeceklerim var" ya da "yeni giri" butonlarına tıkladığımızda açılan text box, yazmaktan vazgeçip sağa sola tıkladığımızda kapanmıyor. sol frame'den ya da ana sayfadan herhangi bir şeyleri tıklamak da kapanmasını sağlamıyor. ancak sekmeyi kapatıp açarak text box'tan kurtulabiliyoruz.

herhangi bir metin yazılmadığı vakit box'ın dışında bir yere tıkladığımızda otomatik kapanmalı, eğer bir metin varsa da uyarı çıkmalı bence.

**Comment by cagataygurturk** [comment]
giri kutusu değişiyor gece
