### ISSUE TITLE
1008 puanla çekirge...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#424]
Raporlayan: yes anastasia

1008 puanla çekirge kaldım, neden oldu böyle nasıl da heveslenmiştim

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/nfidr826t2sqef2cpnqoj32wzbetsnqg38tvhw1bzu1d93qzrg.png)

**Comment by cagataygurturk** [comment]
bir iki dakika beklemen gerekecekti çekirgelikten çıkmışsın zaten otomatik
