### ISSUE TITLE
Merhabalar. Bu sabah...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#481]
Raporlayan: arkadasim essek

Merhabalar. Bu sabah instelayı açtığımda karşıma nick değiştirmem için bir pencere çıktı. Nickimi değiştirdikten sonra ise sistem tüm entrylerimi silerek beni çekirge moduna attı. Eski Nickim Monoditri idi. Mevcut hatayı bildirmek isterim.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/606qageux8zjppusst89q76c53zzehtlhzbsgqmeymxobrg4kp.png)

**Comment by cagataygurturk** [comment]
iletisişme geçildi
