### ISSUE TITLE
paylaşılan sayfa l...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#485]
Raporlayan: anudanilerienkidenberiki

paylaşılan sayfa link olarak gelmiyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/864k2pfh4h21c84hzlyo0nvei8anfisnpx8smn9q4cshkwzjix.png)

**Comment by cagataygurturk** [comment]
http koymak lazım başına
