### ISSUE TITLE
sktch.in sitesinin k...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#500]
Raporlayan: amuda kalkan imam

sktch.in sitesinin kullandığı #sayı uzantısı, sözlüğün giri numaralarıyla çakıştığı için, kişinin paylaştığı link ikiye bölünüyor. biri sktch.in ana sayfasına diğeri konuyla alakasız giri numarasına.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/8ykyssx3zd54txldmhct3hws08atj66r5rqxkn0j05ou398qrk.png)

**Comment by cagataygurturk** [comment]
valla sketch.in mi düzeltsin desem ne desem
