### ISSUE TITLE
daha çok seçenek (...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#511]
Raporlayan: kavalalı

daha çok seçenek (tema rengi, yazı boyutu vs...) oluşturulmalı... özellikle yazı boyutu büyük ve tema göz yorucu...

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/3obt499v0mbvboyf8mx0qybx9i9e5638uf2zobupx6k8ujo35m.png)

**Comment by cagataygurturk** [comment]
yavaş yavaş oluşturuluyor
