### ISSUE TITLE
betaya çağır öze...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#515]
Raporlayan: pedagojik formasyon

betaya çağır özelliği biraz gereğini yitirmedi mi? çağırasım gelmedi sanki zaten burdalar diye düşündüm.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/11kwqtikierqcteb43gy95vlssm96bf8d044unoc1f3d9hpel5.png)

**Comment by cagataygurturk** [comment]
kapattık

**Comment by cagataygurturk** [comment]
kapattık @burakt82
