### ISSUE TITLE
ayarlar kısmında p...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#532]
Raporlayan: zinzinzibidi

ayarlar kısmında profil fotosunu nasıl değiştirebiliyoruz??

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/b4x5qtabr0ffo1s93d7thmvuvy1a540g8ylzrwaixqymrrvv43.png)

**Comment by cagataygurturk** [comment]
profil fotoğrafı profilden değişir
