### ISSUE TITLE
"Giriş" butonuna ba...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#541]
"Giriş" butonuna bastığımda ayrı bir sekme açıyor. kullanıcı adı ve şifreyi yazıp giriş yap dediğimde ayrı bir sekme açıyor. hesaptan çıkış yaparken çıkış yap dediğimde yine ayrı bir sekme açıyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/r98h5novuh3p4un9dqtg2r8p45nxc613gaklx9hsqkive54swy.png)

**Comment by cagataygurturk** [comment]
browser ayarları bozuk sanırım
