### ISSUE TITLE
gece modu eklenebili...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#554]
Raporlayan: chnhf

gece modu eklenebilir mi, ekşide can kurtarıyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/2kvqbng21qo8z3wja7hpmxprvdh5ycq0wmr7a7abyykx1ggcoy.png)

**Comment by cagataygurturk** [comment]
panel->ayarlar->görünüm
