### ISSUE TITLE
Login olurken fotoğ...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#555]
Raporlayan: hadiateyizleroturmayamigeldik

Login olurken fotoğraf geliyor ama kullanıcı adı veya şifre hatası diyor. Evet güvenlik için uyarı öyle çıkarılır. Ama fotoğraf gelince besbelli ki kullanıcı kayıtlı. Ya resim gitsin, ya da yazıyı düzeltin ;)

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/oyit9fycavoqk3f5gxxt832htsip0zcoxvi6agilb7bwbr1soz.png)

**Comment by orhangazi44** [comment]
Adam haklı beyler
