### ISSUE TITLE
selamün aleykümm. ...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#561]
Raporlayan: boom z

selamün aleykümm. itü sözlük v5 neden kullanılmıyor? şifrem doğru olmasına rağmen yanlış diyor. şifremi sıfırlıyorum ama yine aynı hatayı veriyor. v4 e tıklıyorum instela geliyor. sinir oldum panpalar. dayanamıyorum artık! biz nereye yazacaz wondi! nereye! bıktım artık anlıyor musunuz? allah benim belamı versin siz de kurtulun ben de!!!!!! yeter! ühhüü.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/6mqqp3d1vemumzktbtv2gjbcgsza0ti7g8x5cb68pt3bsn53g1.png)

**Comment by cagataygurturk** [comment]
destek bölümünden yazın
