### ISSUE TITLE
Merhabalar,
Giriyi g...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#570]
Raporlayan: tarihselmaddeci

Merhabalar,
Giriyi girdiğimde kaydedilemediğini söylüyor ancak sonrasında sayfayı tekrar başlattığımda girinin girildiğini görüyorum. Hatta 2 defa girdiğim için 2 kez girmiş gözüküyor. Tarayıcı yandex...

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/olblbd7tdobetinw72jgbkdrj8jfzznnky9wchpp504zjrvquf.png)

**Comment by cagataygurturk** [comment]
giri kutusu değişeceğinden bu sorun da otomatik çözülecek
