### ISSUE TITLE
zaman zaman oylama b...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#571]
Raporlayan: pedagojik formasyon

zaman zaman oylama butonlarının hiçbiri çalışmıyor. refresh lersem çalışıyor. ama refrehleyip tekrar o giriyi bulucam da.. ohooo.. neyse oy vermesem de olur deyip geçesim geliyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/5ced686r8mmzxyecfg247h4kdnu9op1u2f78ne0v0nvym9a1qc.png)

**Comment by cagataygurturk** [comment]
@burakt82 tekrar olursa haber ver şimdilik yok gibi
