### ISSUE TITLE
#602 ye ek olarak.

### ISSUE THREAD

**Issue by kendinden-prensli-beyaz-at** [thehivecluster/instela-issues#602]
Şimdi anladım niye kaybolduğunu. diyelimki solda 1. sırada x var, bir altında y kişisi var.x ile konuşuyorsun, o sırada y kişisi sana mesaj atarsa, en üste çıkmaya ayarlanmış y'nin penceresi diyim. ama üste çıkayım derken tamamen gözden kayboluyor. bilmem anlatabildim mi şlksdfds.

**Comment by cagataygurturk** [comment]
anlatabildin bakarız öyleyse
