### ISSUE TITLE
Sakıncalı içerik ...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#614]
Raporlayan: ad astra

Sakıncalı içerik ayarım kapalı olmasına rağmen girilerde böyle uyarılarla karşılaşıyorum. 

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/2f74h6oo75tva0gkke2tgqefos8ixaf0pm47ttw1ypx8pdtasv.png)

**Comment by cagataygurturk** [comment]
denedim sorun yok
