### ISSUE TITLE
www.itusozluk.com ü...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#626]
Raporlayan: dr king schultz

www.itusozluk.com üzerinden profil fotoğrafımı değiştirdim ama instelada etkisni göstermemiş

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/81anmo9tczwngcsvwdle6ctn0ddpfdvoe6b1ulv7ksu14nx10i.png)

**Comment by cagataygurturk** [comment]
bir süre sonra gelir instela'ya da
