### ISSUE TITLE
'yazarlara mesaj ata...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#629]
Raporlayan: sarmaya geldim

'yazarlara mesaj atabilmek için çekirgelik seviyesini geçmeniz gerekir'  yazar olduğum halde neyden sebep çekirgeyim?

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/57c766l675i7m89749sjoezy67fmo2ct9p1fwmm3r5bedkmite.png)

**Comment by cagataygurturk** [comment]
çaylak olmuşsunuz
