### ISSUE TITLE
merhaba,
itüsözlü...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#652]
Raporlayan: th3r4p1st

merhaba,
itüsözlük e geri döndüğümda böyle bir sorun yok. ancak instela da ispikle butonum ve entelijanslığımdan eser yok. bunun özel bir sebebi olup olmadığını merak ediyorum. iyi çalışmalar...

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/nofdd9axgnhncwvvcgj7fywr02h0dz50nke1uoybbfyocujpa3.png)

**Comment by cagataygurturk** [comment]
şikayet butonu var ispiyonlar oradan yapılıyor
