### ISSUE TITLE
Bir başlıkta kendi...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#671]
Raporlayan: lock n load

Bir başlıkta kendi yazdığımız girileri toplu olarak görebileceğimiz fonksiyon vardı, o yok. Olsa ya?

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/i19lgac1p331pcchckjpfi9y54pxuvicxryd2afreis3v5l8p5.png)

**Comment by cagataygurturk** [comment]
takiptekiler kendi girilerini de gösterir
