### ISSUE TITLE
mac'de düzgün göz...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#7]
Raporlayan: radiance

mac'de düzgün gözükmesine karşın pc'de fontlar corrupt oluyor ve özellikle üst kısımları silikleşiyor.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/4a46474e78fddb2e4bd49d132bd0f40a21377.png)

**Comment by cagataygurturk** [comment]
konuyla ilgili dün mailde bilgi vermiştim cevap alamadım.
