### ISSUE TITLE
kapatmak ist,iyorum

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#718]
Raporlayan: damla su

kapatmak ist,iyorum

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/lcaixsrngmen603vrct1aweeitgn13pnfz6drx08jfvpgyl8af.png)

**Comment by larasulfo** [comment]
profilin kapatılma seçeneği olmaması nasıl bir kepazeliktir?
