### ISSUE TITLE
instela ile facebook...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#722]
Raporlayan: yakışıksız prens

instela ile facebook hesabımı senkronize ettim sonrasında buradaki her girim facabookta anasayfada gözükmeye başladı. haber akışında da. bu beni rahatsız etti. uygulamayı faceboktan kaldırmama ragman zaman tunelımde ve haber akısında yıne cıkıyor bu ozellıkten kurtulmak ıstıyorum. teşekkür ederim.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/po9v4qq3a59g20q106jr12j88j589f6y4gu86kcgqmxtmnunud.png)

**Comment by cagataygurturk** [comment]
girilerin altındaki tuşa basılmazsa otomatik paylaşmaz kesinlikle
