### ISSUE TITLE
merhaba arkadaslar b...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#757]
Raporlayan: halilibrahim19075

merhaba arkadaslar benim ismim halilibrahimelveren 

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/pxarf4g7k2j5gj9hwy36jruivazg3s603yg7en9zqs47cdo8cs.png)

**Comment by az3** [comment]
Memnun olduk abi. Teşekkürler.
