### ISSUE TITLE
Kayıt altına alın...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#790]
Raporlayan: salazar slytherin

Kayıt altına alınabiliyor mu ama az evvel denediğim zaman kendi girimi favori ekleyebildiğimi gördüm.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/35jxfik5xgmkbfi2ojnscizmuqlpnhvrmfo2y97vqug19z3yjr.png)

**Comment by mueddib** [comment]
Merhaba,

bende denedim ama kendi girinize oy veremezsiniz dedi ve oylama rakamları 0 olarak kaldı. Tekrar dener misiniz?

**Comment by cagataygurturk** [comment]
favori eklemekten bahsediyor. kendi girini fav eklemek mümkün vitrin özelliği için.

**Comment by mueddib** [comment]
@cagataygurturk şimdi anladım. zaten ticket close edilmiş teşekkürler.
