### ISSUE TITLE
bir hatalı giridir ...

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#84]
Raporlayan: algoritma hatası

bir hatalı giridir kendi görüldüğü üzre düzeltemiyor, aksi gibi silip yeniden giremiyoruz.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/56a38cfbcd4f7e250c3dea3513e16d6410290.png)

**Comment by cagataygurturk** [comment]
@az3 galiba screenshot alan script alamamış ya da ie 6-7 ile girilmiş durumda.

**Comment by cagataygurturk** [comment]
Duplicate #37
