### ISSUE TITLE
404 on url /panel/notifications

### ISSUE THREAD

**Issue by instela** [thehivecluster/instela-issues#98]
Raporlayan: algoritma hatası

404 error occurred
Page not found.
Denetleyici:
    Panel 
  hatası vermekte tümünü göster dendiğinde.

tarayıcı mozilla.

![screenshot](https://bug-image.s3-eu-west-1.amazonaws.com/5ead9cd67f7ad25dba656548e45792bb12461.png)

**Comment by cagataygurturk** [comment]
@az3 pek anlamadım dediğini

**Comment by az3** [comment]
Sol üstteki çan ikonunun üzerine, mouse ile gelip bekleyince, tooltip çıkmıyor. 
Ne işe yaradığını tıklayana kadar anlayamıyoruz.
